import esbuild from "esbuild";

await esbuild.build({
  entryPoints: ["server/_core/index.ts"],
  outdir: "dist",
  bundle: true,
  format: "esm",
  platform: "node",
  external: [
    // All node built-in modules
    "assert",
    "async_hooks",
    "buffer",
    "child_process",
    "cluster",
    "console",
    "constants",
    "crypto",
    "dgram",
    "dns",
    "domain",
    "events",
    "fs",
    "http",
    "http2",
    "https",
    "inspector",
    "module",
    "net",
    "os",
    "path",
    "perf_hooks",
    "process",
    "punycode",
    "querystring",
    "readline",
    "repl",
    "stream",
    "string_decoder",
    "sys",
    "timers",
    "tls",
    "trace_events",
    "tty",
    "url",
    "util",
    "v8",
    "vm",
    "wasi",
    "worker_threads",
    "zlib",
    // Runtime dependencies that should not be bundled
    "dotenv",
    "express",
    "mysql2",
    "drizzle-orm",
    "@trpc/server",
    "bcrypt",
    "jose",
    "cookie",
    "@aws-sdk/*",
    "@tanstack/*",
    "@radix-ui/*",
    // Vite plugins (dev dependencies)
    "@vitejs/plugin-react",
    "vite",
    "@vite*",
    "@builder.io/vite-plugin-jsx-loc",
    "@tailwindcss/vite",
    "tailwindcss",
    "@tailwindcss/*",
  ],
});
